# Generated by Django 2.1 on 2018-08-24 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_boy_girl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='f',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updata_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Boy',
        ),
        migrations.DeleteModel(
            name='Girl',
        ),
    ]
